#!/usr/bin/with-contenv bash

conf_dir="/vdr/config"

# make folders if missing
if [ ! -d $conf_dir/cache ]; then
	mkdir -p $conf_dir/cache
fi

# copy files
if [ -d $conf_dir ]; then
	# copy configs
	cp --archive --recursive --no-dereference --no-clobber /etc/vdr/* $conf_dir/etc
	cp --archive --recursive --no-dereference --no-clobber /var/lib/vdr/* $conf_dir/lib
fi
