#!/usr/bin/with-contenv bash

sys_dir="/vdr/system"	# /etc/vdr

# make folder if missing
if [ ! -d $sys_dir ]; then
	mkdir -p $sys_dir
fi

# copy files
if [ -d $sys_dir ]; then
	#cp --recursive --no-dereference --no-clobber /etc/vdr/* $sys_dir
fi
