name: Updatecli

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  updatecli:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Updatecli
        uses: updatecli/updatecli-action@v2

      - name: Run Updatecli
        run: "updatecli pipeline apply --config ./.updatecli/updatecli.d --values ./.updatecli/values.yml"
        env:
          UPDATECLI_GITHUB_USERNAME: "${{ github.actor }}"
          UPDATECLI_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          UPDATECLI_GITHUB_OWNER: "${{ github.repository_owner }}"

      - name: Keep Workflow Alive
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          # Extract the workflow filename (e.g., updatecli.yml) from the environment reference
          WORKFLOW_FILE=$(basename "${GITHUB_WORKFLOW_REF%%@*}")
          
          printf "Keeping workflow active: %s\n" "$WORKFLOW_FILE"
          
          # Send the PUT request to the GitHub API to reset the 60-day inactivity timer
          gh api -X PUT "repos/${GITHUB_REPOSITORY}/actions/workflows/${WORKFLOW_FILE}/enable"
          
          printf "Workflow successfully kept alive.\n"
