#!/usr/bin/with-contenv bash

conf_dir="/vdr/config"

# make folders if missing
if [ ! -d $conf_dir/cache ]; then
	mkdir -p $conf_dir/cache
fi

# copy files
if [ -d $conf_dir ]; then
	# copy defaults
	cp --no-clobber --recursive /defaults/config/. $conf_dir/
	# copy configs
	cp --recursive --no-dereference --no-clobber /etc/vdr/* $conf_dir/etc
	cp --recursive --no-dereference --no-clobber /var/lib/vdr/* $conf_dir/lib
	cp --recursive --no-dereference $conf_dir/etc/* /etc/vdr
	cp --recursive --no-dereference $conf_dir/lib/* /var/lib/vdr
	# eMail config (msmtp)
	if [ -f "$conf_dir/eMail.conf" ]; then
		msmtp_conf="/etc/msmtprc"
		cp -f $conf_dir/eMail.conf $msmtp_conf
		chown root:root $msmtp_conf
		chmod 640 $msmtp_conf
	fi
fi
