#!/usr/bin/with-contenv bash


main_dir="/vdr"
conf_dir="$main_dir/config"	# /var/lib/vdr
sys_dir="$main_dir/system"	# /etc/vdr


# defaults
if [ -d $main_dir ]; then
	cp -RPpn /defaults/config/* $conf_dir
	cp -RPpn /defaults/system/* $sys_dir
fi


# system
if [ -d $sys_dir ]; then
	# eMail config (msmtp)
	msmtp_conf="/etc/msmtprc"
	if [ -f "$sys_dir/eMail.conf" ]; then
		cp -f $sys_dir/eMail.conf $msmtp_conf
		chown root:root $msmtp_conf
		chmod 640 $msmtp_conf
	fi
fi
