#!/usr/bin/with-contenv bash

### this is also called at finish


## Folders
chown -R vdr:vdr \
	/defaults \
	/etc/vdr/* \
	/home/vdr \
	/srv/vdr \
	/var/cache/vdr \
	/var/lib/vdr \
	/vdr


## Plugins
# live
live_dir="/vdr/config/plugins/live"
if [ -f "$live_dir/live.pem" ]; then
	chmod ug+r $live_dir/live.pem
fi
if [ -f "$live_dir/live-key.pem" ]; then
	chmod ug+r $live_dir/live-key.pem
fi

# ciplus
ci_plus="/vdr/cache/plugins/ciplus/"
if [ -d $ci_plus ] && [ ! -z "$(ls -A $ci_plus)" ]; then
	chmod -f ug+rw *.auth || true
fi
