#!/usr/bin/with-contenv bash

## Folders
chown -R vdr:vdr \
	/defaults \
	/etc/vdr/* \
	/home/vdr \
	/srv/vdr \
	/var/cache/vdr \
	/var/lib/vdr \
	/vdr

chmod -R g+w /home/vdr
chmod -R ug+rw /etc/vdr/*


## Plugins
# live
if [ -f "/vdr/config/plugins/live/live-key.pem" ]; then
	chmod ug+r /vdr/config/plugins/live/live-key.pem
fi
