#!/usr/bin/with-contenv bash

### this is also called at finish


## Folders
chown -R vdr:vdr \
	/defaults \
	/etc/vdr/* \
	/home/vdr \
	/srv/vdr \
	/var/cache/vdr \
	/var/lib/vdr \
	/vdr

chmod 755 \
	/etc/vdr \
	/var/lib/vdr

chmod -R g+w /home/vdr
chmod -R ug+rw /etc/vdr/*


## Plugins
# live
if [ -f "/vdr/config/plugins/live/live-key.pem" ]; then
	chmod ug+r /vdr/config/plugins/live/live-key.pem
fi

# ciplus
ci_plus="/vdr/cache/plugins/ciplus/"
if [ -d $ci_plus ] && [ ! -z "$(ls -A $ci_plus)" ]; then
	chmod -f ug+rw *.auth || true
fi
