#!/usr/bin/with-contenv bash


_isEnabled() {
	plugin=$1;
	enabled=$(vdrctl list --enabled | grep "^$1$")
	if [[ "${enabled_arr[@]}" =~ "${plugin}" ]]; then
		echo 0
	else
		echo 1
	fi
}


# epgsearch
if [ $(_isEnabled "epgsearch") == 1 ]; then
	plug_dir="/var/lib/vdr/plugins/epgsearch"
	loc=$(echo $LANG | cut -d "." -f 1)
	confl_templ="$plug_dir/epgsearchconflmail.templ"
	confl_templ_loc="$plug_dir/epgsearchconflmail-$loc.templ"
	upd_templ="$plug_dir/epgsearchupdmail.templ"
	if [ ! -d $plug_dir ]; then
		mkdir -p $plug_dir
	fi
	if [ -f $confl_templ ] && [ ! -L $confl_templ ]; then
		tmp_templ="/tmp/epgsearchconflmail.templ"
		curl -s -o $tmp_templ https://projects.vdr-developer.org/git/vdr-plugin-epgsearch.git/plain/conf/epgsearchconflmail.templ
		if cmp -s "$confl_templ" "$tmp_templ"; then
			mkdir -p $plug_dir/i18n
			confl_templ_us="i18n/epgsearchconflmail-en_US.templ"
			rm $tmp_templ
			mv $confl_templ $plug_dir/$confl_templ_us
			ln -s $confl_templ_us $confl_templ
		fi
	fi
fi


# vdrmanager
if [ $(_isEnabled "vdrmanager") == 1 ]; then
	plug_dir="/var/lib/vdr/plugins/vdrmanager"
	if [ ! -d $plug_dir ]; then
		mkdir -p $plug_dir
	fi
	if [ ! -e $plug_dir/vdrmanager.pem ]; then
		openssl req -new -x509 -keyout $plug_dir/vdrmanager.key -out $plug_dir/vdrmanager.crt -days 9999 -nodes -batch
		cat $plug_dir/vdrmanager.key > $plug_dir/vdrmanager.pem
		cat $plug_dir/vdrmanager.crt >> $plug_dir/vdrmanager.pem
		rm -f $plug_dir/vdrmanager.key $plug_dir/vdrmanager.crt
	fi
fi
